server:
  port: 8080
spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
     url: jdbc:mysql://{链接地址}:{端口}/{库名}?useSSL=false&serverTimezone=Asia/Shanghai
     username: xxxxxx
     password: xxxxxx
     type: com.zaxxer.hikari.HikariDataSource
     hikari:
       minimum-idle: 5
       maximum-pool-size: 15
       auto-commit: true
       idle-timeout: 300000
       pool-name: wejuaiPool
       max-lifetime: 1800000
       connection-timeout: 30000
       connection-test-query: SELECT 1
       connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  data:
    mongodb:
      uri: mongodb://{账号}:{密码}@{连接地址}:{端口}/{库名}?authMechanism=SCRAM-SHA-1&socketTimeoutMS=3000&maxIdleTimeMS=180000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
management:
  endpoints:
    web:
      exposure:
        include: info,health
weixin:
  offi-origin-id: xxxxxxx #公众号原始id
  app-origin-id: xxxxxxx #小程序原始id
  open-id: xxxxxxx #开放平台 accessKey
  open-secret: xxxxxx #开放平台 accessSecret
  offi-id: xxxxxx #公众号 accessKey
  offi-secret: xxxxxx #公众号 accessSecret
  app-id: xxxxxx #小程序accessKey
  app-secret: xxxxxx #小程序 accessSecret
  app-audit: xxxxxx #审核通知模版消息id
  app-reply: xxxxxx #应用收到回复的模版消息id
info:
  app:
    name: wejuai-weixin-callback
    version: 1.0.0