logging:
  config: classpath:logConfig.xml
spring:
  data:
    mongodb:
      uri: mongodb://{账号}:{密码}@{连接地址}:{端口}/{库名}?authMechanism=SCRAM-SHA-1&socketTimeoutMS=3000&maxIdleTimeMS=180000
  datasource:
    url: jdbc:mysql://{链接地址}:{端口}/{库名}?useSSL=false&serverTimezone=Asia/Shanghai